from __future__ import annotations

import email
from datetime import datetime
from email import policy
from pathlib import Path
from typing import Any

import polars as pl
import pytest

from carta import runner
from carta.loader import LoadedDefinition
from carta.validator import validate_all


def _read_eml(path: Path) -> email.message.EmailMessage:
    msg = email.message_from_bytes(path.read_bytes(), policy=policy.default)
    assert isinstance(msg, email.message.EmailMessage)
    return msg


def _validated(raw: dict[str, Any]) -> Any:
    ld = LoadedDefinition(
        source_path=Path("definitions/x.py"),
        sql_path=Path("definitions/x.sql"),
        sql_text="SELECT 1 FROM dual",
        raw=raw,
    )
    valid, errors = validate_all([ld], active=[raw["key"]])
    assert errors == [], errors
    return valid[0]


@pytest.fixture
def ctx(tmp_path: Path) -> runner.RunContext:
    return runner.RunContext(out_dir=tmp_path, run_dt=datetime(2026, 5, 16, 14, 30))


def _stub_execute(df: pl.DataFrame) -> Any:
    def _impl(conn: Any, sql: str, params: dict[str, Any]) -> pl.DataFrame:
        return df

    return _impl


def test_format_template_substitutes_known_placeholders() -> None:
    out = runner.format_template(
        "Hello {key} on {run_date} — {row_count:,} rows",
        run_dt=datetime(2026, 1, 2, 9, 5),
        row_count=4217,
        key="enrollment",
    )
    assert out == "Hello enrollment on 2026-01-02 — 4,217 rows"


def test_append_footer_format() -> None:
    out = runner.append_footer(
        "Body.",
        run_dt=datetime(2026, 5, 16, 14, 30),
        row_count=1234,
        key="enrollment_by_term",
    )
    assert "Generated by carta on 2026-05-16 14:30." in out
    assert "Rows: 1,234. Query: enrollment_by_term." in out


def test_run_one_ok_writes_xlsx_and_eml(
    monkeypatch: pytest.MonkeyPatch, ctx: runner.RunContext, sample_df: pl.DataFrame
) -> None:
    monkeypatch.setattr(runner.db, "execute", _stub_execute(sample_df))
    ctx.run_dir.mkdir(parents=True, exist_ok=True)
    d = _validated(
        {
            "key": "report",
            "recipients": ["a@x.com"],
            "subject": "S {run_date}",
            "body": "Body {row_count}",
        }
    )
    result = runner.run_one(d, conn=object(), ctx=ctx)
    assert result.status == "ok"
    assert result.rows == 3
    assert result.xlsx_name == "report.xlsx"
    assert result.eml_name == "report.eml"
    assert (ctx.run_dir / "report.xlsx").is_file()
    assert (ctx.run_dir / "report.eml").is_file()

    msg = _read_eml(ctx.run_dir / "report.eml")
    assert msg["Subject"] == "S 2026-05-16"
    body_part = next(
        p for p in msg.iter_parts() if p.get_content_disposition() != "attachment"
    )
    body = body_part.get_content()
    assert "Body 3" in body
    assert "Generated by carta on 2026-05-16 14:30." in body  # footer default


def test_run_one_on_empty_skip(
    monkeypatch: pytest.MonkeyPatch, ctx: runner.RunContext
) -> None:
    monkeypatch.setattr(runner.db, "execute", _stub_execute(pl.DataFrame()))
    d = _validated(
        {
            "key": "empty_one",
            "recipients": ["a@x.com"],
            "subject": "S",
            "body": "B",
            "on_empty": "skip",
        }
    )
    result = runner.run_one(d, conn=object(), ctx=ctx)
    assert result.status == "skip"
    assert result.rows == 0
    # No files written for skip
    assert not (ctx.run_dir / "empty_one.xlsx").exists()
    assert not (ctx.run_dir / "empty_one.eml").exists()


def test_run_one_on_empty_error(
    monkeypatch: pytest.MonkeyPatch, ctx: runner.RunContext
) -> None:
    monkeypatch.setattr(runner.db, "execute", _stub_execute(pl.DataFrame()))
    d = _validated(
        {
            "key": "empty_two",
            "recipients": ["a@x.com"],
            "subject": "S",
            "body": "B",
            "on_empty": "error",
        }
    )
    result = runner.run_one(d, conn=object(), ctx=ctx)
    assert result.status == "error"
    assert "empty result" in (result.message or "")


def test_run_one_on_empty_send(
    monkeypatch: pytest.MonkeyPatch, ctx: runner.RunContext
) -> None:
    monkeypatch.setattr(runner.db, "execute", _stub_execute(pl.DataFrame()))
    ctx.run_dir.mkdir(parents=True, exist_ok=True)
    d = _validated(
        {
            "key": "empty_three",
            "recipients": ["a@x.com"],
            "subject": "S",
            "body": "B",
            "on_empty": "send",
        }
    )
    result = runner.run_one(d, conn=object(), ctx=ctx)
    assert result.status == "ok"
    assert result.rows == 0
    assert (ctx.run_dir / "empty_three.xlsx").is_file()
    assert (ctx.run_dir / "empty_three.eml").is_file()


def test_run_one_no_footer_when_disabled(
    monkeypatch: pytest.MonkeyPatch, ctx: runner.RunContext, sample_df: pl.DataFrame
) -> None:
    monkeypatch.setattr(runner.db, "execute", _stub_execute(sample_df))
    ctx.run_dir.mkdir(parents=True, exist_ok=True)
    d = _validated(
        {
            "key": "nofoot",
            "recipients": ["a@x.com"],
            "subject": "S",
            "body": "Hello.",
            "footer": False,
        }
    )
    runner.run_one(d, conn=object(), ctx=ctx)
    msg = _read_eml(ctx.run_dir / "nofoot.eml")
    body = next(
        p for p in msg.iter_parts() if p.get_content_disposition() != "attachment"
    ).get_content()
    assert "Generated by carta" not in body


def test_run_all_isolates_per_definition_errors(
    monkeypatch: pytest.MonkeyPatch, ctx: runner.RunContext, sample_df: pl.DataFrame
) -> None:
    def execute(conn: Any, sql: str, params: dict[str, Any]) -> pl.DataFrame:
        if params.get("explode"):
            raise RuntimeError("kaboom")
        return sample_df

    monkeypatch.setattr(runner.db, "execute", execute)
    good = _validated(
        {"key": "good", "recipients": ["a@x.com"], "subject": "S", "body": "B"}
    )
    bad = _validated(
        {
            "key": "bad",
            "recipients": ["a@x.com"],
            "subject": "S",
            "body": "B",
            "params": {"explode": True},
        }
    )
    results = runner.run_all([good, bad], conn=object(), ctx=ctx)
    assert [r.status for r in results] == ["ok", "error"]
    assert "kaboom" in (results[1].message or "")


def test_filename_template_resolves(
    monkeypatch: pytest.MonkeyPatch, ctx: runner.RunContext, sample_df: pl.DataFrame
) -> None:
    monkeypatch.setattr(runner.db, "execute", _stub_execute(sample_df))
    ctx.run_dir.mkdir(parents=True, exist_ok=True)
    d = _validated(
        {
            "key": "weekly",
            "recipients": ["a@x.com"],
            "subject": "S",
            "body": "B",
            "filename": "{key}_{run_date}.xlsx",
        }
    )
    result = runner.run_one(d, conn=object(), ctx=ctx)
    assert result.xlsx_name == "weekly_2026-05-16.xlsx"
    assert result.eml_name == "weekly_2026-05-16.eml"
