"""Per-definition pipeline: query -> xlsx -> .eml draft, with error isolation."""

from __future__ import annotations

import traceback
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Literal

from carta import db, email_draft, excel
from carta.validator import ValidatedDefinition


@dataclass
class RunResult:
    key: str
    status: Literal["ok", "skip", "error"]
    rows: int = 0
    xlsx_name: str | None = None
    eml_name: str | None = None
    message: str | None = None
    traceback: str | None = None


@dataclass(frozen=True)
class RunContext:
    out_dir: Path
    run_dt: datetime

    @property
    def run_dir(self) -> Path:
        return self.out_dir / self.run_dt.strftime("%Y-%m-%d_%H%M")


def format_template(s: str, *, run_dt: datetime, row_count: int, key: str) -> str:
    return s.format(
        run_date=run_dt.strftime("%Y-%m-%d"),
        run_datetime=run_dt.strftime("%Y-%m-%d %H:%M"),
        row_count=row_count,
        key=key,
    )


def append_footer(body: str, *, run_dt: datetime, row_count: int, key: str) -> str:
    footer = (
        "\n\n—\n"
        f"Generated by carta on {run_dt.strftime('%Y-%m-%d %H:%M')}.\n"
        f"Rows: {row_count:,}. Query: {key}.\n"
    )
    return body + footer


def run_all(
    active: list[ValidatedDefinition],
    conn: Any,
    ctx: RunContext,
) -> list[RunResult]:
    ctx.run_dir.mkdir(parents=True, exist_ok=True)
    return [run_one(d, conn, ctx) for d in active]


def run_one(d: ValidatedDefinition, conn: Any, ctx: RunContext) -> RunResult:
    defn = d.definition
    try:
        df = db.execute(conn, d.sql_text, defn.params)
        rows = df.height

        if rows == 0:
            if defn.on_empty == "skip":
                return RunResult(key=d.key, status="skip", rows=0, message="on_empty='skip'")
            if defn.on_empty == "error":
                return RunResult(
                    key=d.key, status="error", rows=0, message="empty result (on_empty='error')"
                )
            # "send" falls through and produces draft with empty body table.

        xlsx_name = format_template(
            defn.filename, run_dt=ctx.run_dt, row_count=rows, key=d.key
        )
        eml_name = Path(xlsx_name).stem + ".eml"
        xlsx_path = ctx.run_dir / xlsx_name
        eml_path = ctx.run_dir / eml_name

        excel.write_xlsx(df, xlsx_path, defn.sheet_name)

        subject = format_template(defn.subject, run_dt=ctx.run_dt, row_count=rows, key=d.key)
        body = format_template(defn.body, run_dt=ctx.run_dt, row_count=rows, key=d.key)
        if defn.footer:
            body = append_footer(body, run_dt=ctx.run_dt, row_count=rows, key=d.key)

        email_draft.write_eml(
            eml_path,
            recipients=defn.recipients,
            cc=defn.cc,
            subject=subject,
            body_text=body,
            attachment_path=xlsx_path,
        )

        return RunResult(
            key=d.key,
            status="ok",
            rows=rows,
            xlsx_name=xlsx_name,
            eml_name=eml_name,
        )
    except Exception as e:
        return RunResult(
            key=d.key,
            status="error",
            message=f"{type(e).__name__}: {e}",
            traceback=traceback.format_exc(),
        )
